# Generated by Django 2.2 on 2019-04-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='users_id',
            field=models.IntegerField(default=0),
        ),
    ]
